name: create zip
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create zip file"
        run: zip -r youcog.zip . -x ".github/*" -x ".git/*"
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: youcog.zip
          path: youcog.zip
          retention-days: 5
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download extension artifact
        uses: actions/download-artifact@v2
        with:
          name: youcog.zip
      - name: Publish to chrome web store
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: jnlhbeanefgkikffdjnmajjfadpbfeop
          zip: youcog.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
